// ═══ The shipped weather sounds (EditorDeps/EngineContent/Audio/Weather) ═════
// Generated by weather_sound_gen and COMMITTED, so nothing rebuilds them on the
// way to this test — which is exactly why it needs one. Every project hears its
// weather through these when a Weather component leaves a sound slot empty
// (WeatherAudio, DefaultAssets.h kEngineWeather*SoundId), in the editor from the
// engine content next to the executable and in a shipped game from the .hpak.
//
// What is checked is what only the FILES can get wrong: that the five assets are
// there under the UUIDs the code asks for, that the four loops really loop (a
// click at the seam is the one flaw a looping bed cannot hide), that nothing is
// silent, clipped or blown up, that an export packs them and that the weather of
// a shipped game finds and plays them. How the beds are mixed is
// test_weather_audio.cpp's business.

#include "doctest.h"
#include "TestFsUtil.h"

#include <ContentManager/Assets.h>
#include <ContentManager/ContentManager.h>
#include <ContentManager/DefaultAssets.h>
#include <ContentManager/HAsset.h>
#include <Hpak/HpakReader.h>
#include <Hpak/ProjectExporter.h>
#include <HorizonScene/AudioEngine.h>
#include <HorizonScene/HorizonWorld.h>
#include <HorizonScene/WeatherAudio.h>
#include <HorizonScene/WeatherSystem.h>
#include <HorizonScene/Components/EnvironmentComponent.h>
#include <HorizonScene/Components/WeatherComponent.h>
#include <Types/UUID.h>

#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <string>
#include <vector>

#ifdef HE_EDITOR_DEPS_DIR
namespace
{
namespace fs = std::filesystem;

const fs::path& engineRoot()
{
	static const fs::path p = fs::path(HE_EDITOR_DEPS_DIR) / "EngineContent";
	return p;
}

struct Clip
{
	const char* name;
	HE::UUID    id;
	bool        loops;
};
// The order of DefaultAssets.h and of weather_sound_gen's table.
const Clip kClips[] = {
	{ "Rain",    HE::kEngineWeatherRainSoundId,    true  },
	{ "Wind",    HE::kEngineWeatherWindSoundId,    true  },
	{ "Snow",    HE::kEngineWeatherSnowSoundId,    true  },
	{ "Storm",   HE::kEngineWeatherStormSoundId,   true  },
	{ "Thunder", HE::kEngineWeatherThunderSoundId, false },
};

std::string clipPath(const Clip& c) { return std::string("Engine/Audio/Weather/") + c.name + ".hasset"; }
fs::path    clipFile(const Clip& c) { return engineRoot() / "Audio" / "Weather" / (std::string(c.name) + ".hasset"); }

// A throwaway project directory: a load must never be able to write into the tree.
struct Scratch
{
	fs::path path;
	explicit Scratch(const char* tag)
	{
		path = fs::temp_directory_path() /
		       (std::string("he_engine_wxs_") + tag + "_" +
		        std::to_string(std::chrono::steady_clock::now().time_since_epoch().count()));
		he_test::removeAllQuiet(path);
		fs::create_directories(path / "Content");
	}
	~Scratch() { he_test::removeAllQuiet(path); }
	std::string content() const { return (path / "Content").string(); }
};

std::vector<uint8_t> readBytes(const fs::path& p)
{
	std::ifstream f(p, std::ios::binary);
	return std::vector<uint8_t>(std::istreambuf_iterator<char>(f), std::istreambuf_iterator<char>());
}

// The asset's UUID the way the SFTP publish scan reads it (EngineContentPublish
// readAssetUuid): META after the 2-byte type, in a version-2 file or newer. A file
// this cannot read is skipped by "Publish Engine Content" without a word.
bool publishScanUuid(const std::vector<uint8_t>& bytes, HE::UUID& out)
{
	HAsset::Reader reader;
	if (!reader.openData(bytes)) return false;
	if (reader.header().version < 2) return false;
	const auto* meta = reader.findChunk(HAsset::CHUNK_META);
	if (!meta) return false;
	size_t off = sizeof(uint16_t);
	return HAsset::Reader::readPOD(meta->data, off, out.hi) && HAsset::Reader::readPOD(meta->data, off, out.lo);
}

std::vector<int16_t> samplesOf(const AudioAsset& a)
{
	std::vector<int16_t> s(a.audioData.size() / sizeof(int16_t));
	if (!s.empty()) std::memcpy(s.data(), a.audioData.data(), s.size() * sizeof(int16_t));
	return s;
}

double rmsOf(const std::vector<int16_t>& s, size_t begin, size_t end)
{
	double sq = 0.0;
	for (size_t i = begin; i < end; ++i) { const double v = s[i] / 32768.0; sq += v * v; }
	return end > begin ? std::sqrt(sq / static_cast<double>(end - begin)) : 0.0;
}

double peakOf(const std::vector<int16_t>& s)
{
	int peak = 0;
	for (int16_t v : s) peak = std::max(peak, std::abs(static_cast<int>(v)));
	return peak / 32768.0;
}

// |first - last| measured in typical steps between neighbouring samples: about 1
// where the seam is an ordinary pair of samples, several for a click.
double seamRatio(const std::vector<int16_t>& s)
{
	double sq = 0.0;
	for (size_t i = 1; i < s.size(); ++i) { const double d = (s[i] - s[i - 1]) / 32768.0; sq += d * d; }
	const double step = std::sqrt(sq / static_cast<double>(s.size() - 1));
	return step > 0.0 ? std::fabs((s.front() - s.back()) / 32768.0) / step : 0.0;
}

constexpr double kSeamLimit = 4.0;   // the files measure 0 to 1.3

const AudioAsset* loadClip(ContentManager& cm, const Clip& c)
{
	const HE::UUID id = cm.loadAsset(clipPath(c));
	return id == HE::UUID{} ? nullptr : cm.getAudio(id);
}
} // namespace

TEST_CASE("Weather sounds: five small mono PCM16 assets under Engine/Audio/Weather, with the UUIDs the code asks for")
{
	Scratch s("files");
	ContentManager cm(s.content());
	cm.setEngineContentRoot(engineRoot().string());

	uintmax_t total = 0;
	for (const Clip& c : kClips)
	{
		CAPTURE(std::string(c.name));
		REQUIRE(fs::exists(clipFile(c)));
		total += fs::file_size(clipFile(c));

		// The UUID WeatherAudio asks the ContentManager for (DefaultAssets.h) is the
		// one in the file: this is what makes "empty slot = engine sound" work.
		const HE::UUID id = cm.loadAsset(clipPath(c));
		CHECK(id == c.id);
		CHECK(cm.assetType(id) == HE::AssetType::Audio);
		const AudioAsset* a = cm.getAudio(id);
		REQUIRE(a);
		CHECK(a->name == c.name);
		CHECK(a->encoding == AudioEncoding::PCM16);
		CHECK(a->channels == 1);
		CHECK(a->sampleRate >= 8000);
		CHECK(a->sampleRate <= 48000);
		CHECK(a->edit.isDefault());   // shipped untouched: no trim, curve, EQ or bus baked in

		// A bed that is shorter than a few seconds repeats audibly.
		const double seconds = static_cast<double>(audioPcmFrameCount(*a)) / a->sampleRate;
		CHECK(seconds >= (c.loops ? 5.0 : 3.0));
		CHECK(seconds <= 12.0);
	}
	// Small is part of the contract: these ride in every editor download, every
	// git clone and, by default, every exported pak. A Vorbis encoder would make
	// them ten times smaller (see weather_sound_gen); until there is one, this keeps
	// the PCM from growing unnoticed.
	CHECK(total < 1500u * 1024u);
}

TEST_CASE("Weather sounds: the SFTP publish scan reads their UUIDs, and nothing else claims the block")
{
	// "Publish Engine Content" walks the tree for every .hasset and lists the ones
	// whose UUID it can read. This is that read, on the real files, plus the check
	// that the 0x500 block belongs to the weather sounds alone — two assets with one
	// UUID make the manifest, the registry and the pak pick one of them blindly.
	for (const Clip& c : kClips)
	{
		CAPTURE(std::string(c.name));
		HE::UUID id;
		REQUIRE(publishScanUuid(readBytes(clipFile(c)), id));
		CHECK(id == c.id);
		CHECK(id != HE::UUID{});
	}

	int inBlock = 0;
	std::error_code ec;
	for (const auto& p : fs::recursive_directory_iterator(engineRoot(), ec))
	{
		if (!p.is_regular_file(ec) || p.path().extension() != ".hasset") continue;
		HE::UUID id;
		if (!publishScanUuid(readBytes(p.path()), id)) continue;
		if (id.hi < 0x500 || id.hi > 0x5FF) continue;
		++inBlock;
		const std::string rel = fs::relative(p.path(), engineRoot()).generic_string();
		CHECK_MESSAGE(rel.rfind("Audio/Weather/", 0) == 0, rel << " uses the weather sounds' UUID block");
	}
	CHECK(inBlock == static_cast<int>(std::size(kClips)));
}

TEST_CASE("Weather sounds: the loops are seamless, the levels sane, the thunder starts and ends at silence")
{
	Scratch s("audio");
	ContentManager cm(s.content());
	cm.setEngineContentRoot(engineRoot().string());

	for (const Clip& c : kClips)
	{
		CAPTURE(std::string(c.name));
		const AudioAsset* a = loadClip(cm, c);
		REQUIRE(a);
		const std::vector<int16_t> x = samplesOf(*a);
		REQUIRE(x.size() > 10000);

		// Loud enough to hear, not clipped, not a spike with a little noise around it.
		const double rms  = rmsOf(x, 0, x.size());
		const double peak = peakOf(x);
		CHECK(rms >= 0.03);
		CHECK(peak <= 0.97);
		CHECK(peak < 32767.0 / 32768.0);

		if (c.loops)
		{
			// Crest factor: a filter that blows up for a moment leaves one burst in
			// near silence (the storm once did: 30 times its own level for half a
			// second), which shows as a peak far above the RMS.
			CHECK(peak / rms < 8.0);
			CHECK(rms <= 0.30);

			// Every half second is a bed, not a hole and not a burst.
			const size_t win = static_cast<size_t>(a->sampleRate) / 2;
			for (size_t at = 0; at + win <= x.size(); at += win)
			{
				const double w = rmsOf(x, at, at + win);
				CAPTURE(at);
				CHECK(w >= 0.35 * rms);
				CHECK(w <= 2.2 * rms);
			}

			// The seam: the last sample runs into the first like any two neighbours.
			CHECK(seamRatio(x) < kSeamLimit);
		}
		else
		{
			// A one-shot starts and ends at zero, so nothing clicks when it is
			// started, and the roll has died away by the end.
			CHECK(std::abs(static_cast<int>(x.front())) <= 2);
			CHECK(std::abs(static_cast<int>(x.back())) <= 2);
			CHECK(peak >= 0.5);
			const size_t tail = static_cast<size_t>(a->sampleRate) / 2;
			CHECK(rmsOf(x, x.size() - tail, x.size()) < 0.05 * peak);
			// …and it is a strike, not a hum: the loudest sample is early.
			size_t at = 0;
			for (size_t i = 0; i < x.size(); ++i)
				if (std::abs(static_cast<int>(x[i])) > std::abs(static_cast<int>(x[at]))) at = i;
			CHECK(at < static_cast<size_t>(a->sampleRate) * 3 / 2);
		}
	}
}

TEST_CASE("Weather sounds: the seam check really detects a cut loop (negative control)")
{
	// A loop cut anywhere but at its period clicks. The same measure must see that on
	// the wind (a slow, low sound where a click is plain), or "seamless" above would
	// pass for any file.
	Scratch s("control");
	ContentManager cm(s.content());
	cm.setEngineContentRoot(engineRoot().string());
	const AudioAsset* wind = loadClip(cm, kClips[1]);
	REQUIRE(wind);
	const std::vector<int16_t> x = samplesOf(*wind);
	REQUIRE(seamRatio(x) < kSeamLimit);

	int cuts = 0, clicks = 0;
	for (size_t cut = 1000; cut < x.size() / 2; cut += 997, ++cuts)
	{
		const std::vector<int16_t> shortened(x.begin(), x.end() - static_cast<std::ptrdiff_t>(cut));
		if (seamRatio(shortened) >= kSeamLimit) ++clicks;
	}
	// Not every cut lands on a big jump (the wind wanders around zero), but a good
	// share of them must, or the limit above is not measuring anything.
	CHECK(clicks >= 5);
	CHECK(clicks * 8 >= cuts);
}

TEST_CASE("Weather sounds: an export packs them and a shipped game reads them back sample for sample")
{
	// ExportDialogPanel hands the exporter the whole engine content root, and
	// HpakWriter packs every .hasset of every root, so the sounds ship without a scene
	// naming them (which is why collectAssetRefs must NOT list the defaults).
	Scratch s("export");
	const fs::path engineDir = s.path / "engine";
	const fs::path outputDir = s.path / "out";
	fs::create_directories(engineDir / "Audio" / "Weather");
	for (const Clip& c : kClips)
		fs::copy_file(clipFile(c), engineDir / "Audio" / "Weather" / (std::string(c.name) + ".hasset"));

	ExportSettings settings;               // the export dialog's defaults: compressed
	settings.engineContentDir = engineDir;
	const auto result = ProjectExporter::exportProject(
		fs::path(s.content()), "WxGame", "", outputDir, settings);
	REQUIRE(result.success);
	CHECK(result.assetsPacked == static_cast<int>(std::size(kClips)));

	const fs::path pakPath = outputDir / "WxGame.hpak";
	REQUIRE(fs::exists(pakPath));
	{
		HpakReader reader;
		REQUIRE(reader.open(pakPath.string()));
		for (const Clip& c : kClips)
		{
			CAPTURE(std::string(c.name));
			CHECK(reader.hasEntry(c.id));
		}
	}

	// A fresh manager with only the pak: no engine content root, like the game.
	ContentManager shipped;
	REQUIRE(shipped.mountPak(pakPath.string()));
	Scratch s2("reference");
	ContentManager editor(s2.content());
	editor.setEngineContentRoot(engineRoot().string());
	for (const Clip& c : kClips)
	{
		CAPTURE(std::string(c.name));
		REQUIRE(shipped.ensureResident(c.id));
		const AudioAsset* got  = shipped.getAudio(c.id);
		const AudioAsset* want = loadClip(editor, c);
		REQUIRE(got);
		REQUIRE(want);
		CHECK(got->sampleRate == want->sampleRate);
		CHECK(got->channels == want->channels);
		CHECK(got->encoding == want->encoding);
		CHECK(got->audioData == want->audioData);
	}
}

namespace
{
// A world with a Sky and a Weather entity settled on `kind`.
struct WxRig
{
	HorizonWorld          world;
	AudioEngine           engine;
	WeatherAudio::State   state { 99u };
	WeatherComponent*     weather = nullptr;

	explicit WxRig(WeatherKind kind)
	{
		REQUIRE(engine.init(true));   // no device: voices exist, nothing is played out loud
		world.addSky();
		const Entity wxE = world.addWeather();
		weather = &world.registry().get<WeatherComponent>(wxE);
		weather->currentKind = weather->targetKind = kind;
		weather->intensity   = 1.0f;
		WeatherSystem::update(world, 0.016f);
	}
	~WxRig() { WeatherAudio::stop(state, engine); engine.shutdown(); }

	// Run weather and its sound for `seconds`; true once a thunder roll was heard.
	bool run(ContentManager& content, float seconds, float step = 0.1f)
	{
		bool thunder = false;
		for (float t = 0.0f; t < seconds - 1e-4f; t += step)
		{
			WeatherSystem::update(world, step);
			WeatherAudio::Frame f;
			f.realDt = step;
			f.gameDt = step;
			WeatherAudio::update(state, world, engine, content, f);
			if (!state.thunder.empty()) thunder = true;
		}
		return thunder;
	}
	WeatherAudio::State::Bed& bed(WeatherAudio::Layer l) { return state.beds[static_cast<size_t>(l)]; }
};

// The weather of a project with no sound of its own: every default must be found,
// loaded and playing, wherever the ContentManager gets the files from.
void checkStormPlaysTheDefaults(ContentManager& content)
{
	using WeatherAudio::Layer;
	WxRig rig(WeatherKind::Storm);
	const bool thunder = rig.run(content, 40.0f);

	// A storm is rain, wind and the storm bed together; there is no snow in it.
	const struct { Layer layer; HE::UUID id; } expected[] = {
		{ Layer::Rain,  HE::kEngineWeatherRainSoundId  },
		{ Layer::Wind,  HE::kEngineWeatherWindSoundId  },
		{ Layer::Storm, HE::kEngineWeatherStormSoundId },
	};
	for (const auto& e : expected)
	{
		CAPTURE(WeatherAudio::layerName(e.layer));
		WeatherAudio::State::Bed& bed = rig.bed(e.layer);
		REQUIRE(bed.handle != 0);
		CHECK(bed.asset == e.id);
		CHECK(rig.engine.isPlaying(bed.handle));
		CHECK(bed.gain > 0.1f);
	}
	CHECK(rig.bed(Layer::Snow).handle == 0);
	// …and the lightning of the storm was answered by the default thunder.
	CHECK(thunder);
}
} // namespace

TEST_CASE("Weather sounds: the editor's weather plays the engine defaults from the engine content folder")
{
	Scratch s("editor");
	ContentManager cm(s.content());
	cm.setEngineContentRoot(engineRoot().string());
	cm.scanContentDirectory();   // what the editor does on project open: UUIDs → files
	checkStormPlaysTheDefaults(cm);
}

TEST_CASE("Weather sounds: a shipped game's weather plays the engine defaults from the pak")
{
	Scratch s("game");
	const fs::path engineDir = s.path / "engine";
	const fs::path outputDir = s.path / "out";
	fs::create_directories(engineDir / "Audio" / "Weather");
	for (const Clip& c : kClips)
		fs::copy_file(clipFile(c), engineDir / "Audio" / "Weather" / (std::string(c.name) + ".hasset"));
	ExportSettings settings;
	settings.engineContentDir = engineDir;
	REQUIRE(ProjectExporter::exportProject(fs::path(s.content()), "WxGame2", "", outputDir, settings).success);

	ContentManager game;   // no project content, no engine content root: the pak is all there is
	REQUIRE(game.mountPak((outputDir / "WxGame2.hpak").string()));
	checkStormPlaysTheDefaults(game);
}
#endif // HE_EDITOR_DEPS_DIR
