#include "doctest.h"

#include "DocsLibrary.h"

#include <string>

// ── The in-editor manual ─────────────────────────────────────────────────────
// Two things are checked here, and they fail for very different reasons.
//
//  * The SHIPPED bundle (EditorDeps/Docs/he-docs.json, regenerated by
//    scripts/build_docs_bundle.py). If the conversion loses the tables, drops a
//    page or produces a section without text, Help ▸ Documentation opens onto a
//    blank panel — and nothing else in the build would notice, because the
//    bundle is data.
//  * The SEARCH, against hand-written bundles. Ranking is the whole product
//    here: a search box that answers "shadow" with the section that mentions it
//    in passing, ahead of the one titled "Shadows", is worse than no search box.

using namespace HE::Ed::Docs;

namespace
{
	// The bundle as it sits in the repo — the same file CMake copies next to the
	// editor. Passed in by the build (tests/CMakeLists.txt) rather than found by
	// walking up from the working directory, which differs between ctest, an IDE
	// runner and a packaged test binary.
	Library loadShipped()
	{
		Library lib;
#ifdef HE_DOCS_BUNDLE_PATH
		lib.load(HE_DOCS_BUNDLE_PATH);
#endif
		return lib;
	}

	std::string firstTitle(const Library& lib, const std::vector<Hit>& hits)
	{
		if (hits.empty()) return "(no hits)";
		return lib.pages()[hits[0].page].sections[hits[0].section].title;
	}

	// A miniature bundle: enough structure to drive the parser and the ranking
	// without depending on a sentence somebody may reword on the website.
	const char* kMiniBundle = R"JSON({
	  "version": 1,
	  "generated": "2026-08-25",
	  "baseUrl": "https://example.invalid/docs/",
	  "groups": [ { "title": "Manual", "pages": ["alpha", "beta"] } ],
	  "pages": [
	    { "id": "alpha", "file": "alpha.html", "title": "Alpha Page",
	      "summary": "The first page.",
	      "sections": [
	        { "id": "shadows", "title": "Shadows", "eyebrow": "Lighting",
	          "text": "Cascaded shadow maps follow the sun.",
	          "blocks": [
	            { "k": "lead", "r": [ { "t": "Cascaded ", "s": "" },
	                                  { "t": "shadow maps", "s": "b" },
	                                  { "t": " follow the sun.", "s": "" } ] },
	            { "k": "table", "head": [ [ { "t": "Setting", "s": "" } ] ],
	              "rows": [ [ [ { "t": "shadowDistance", "s": "c" } ] ] ] },
	            { "k": "callout", "tone": "warning",
	              "blocks": [ { "k": "p", "r": [ { "t": "Metal only.", "s": "" } ] } ] }
	          ] },
	        { "id": "misc", "title": "Miscellany", "eyebrow": "",
	          "text": "A passing mention of shadow, and of highlight handling.",
	          "blocks": [ { "k": "p", "r": [ { "t": "A passing mention.", "s": "" } ] } ] }
	      ] },
	    { "id": "beta", "file": "beta.html", "title": "Beta Page", "summary": "",
	      "sections": [
	        { "id": "code", "title": "Listings", "eyebrow": "",
	          "text": "onUpdate runs every frame.",
	          "blocks": [ { "k": "code", "title": "spin.lua",
	                        "text": "function M.onUpdate(self, dt)\nend" },
	                      { "k": "ul", "items": [ [ { "t": "one", "s": "" } ],
	                                              [ { "t": "two", "s": "" } ] ] },
	                      { "k": "figure", "src": "shot.jpg", "alt": "A screenshot" },
	                      { "k": "flow", "steps": [ { "label": "Extract", "sub": "scene" } ] } ] }
	      ] }
	  ]
	})JSON";
} // namespace

TEST_CASE("docs bundle: the shipped file loads and is complete")
{
	Library lib = loadShipped();
	REQUIRE_MESSAGE(lib.loaded(), lib.error());

	// Wide enough to catch a conversion that silently produced one page, narrow
	// enough not to fail every time a page is added to the website.
	CHECK(lib.pages().size() >= 8);
	CHECK(!lib.generated().empty());
	CHECK(!lib.groups().empty());

	int sections = 0, blocks = 0, tables = 0, code = 0;
	for (const Page& p : lib.pages())
	{
		CHECK(!p.id.empty());
		CHECK(!p.title.empty());
		CHECK(!p.file.empty());
		CHECK(!p.sections.empty());
		for (const Section& s : p.sections)
		{
			++sections;
			CHECK(!s.title.empty());
			// A section with no searchable text is invisible to the search box and
			// blank in the reader — exactly the failure the generator must not have.
			CHECK(!s.text.empty());
			CHECK(!s.blocks.empty());
			CHECK(s.page == static_cast<int>(&p - lib.pages().data()));
			for (const Block& b : s.blocks)
			{
				++blocks;
				CHECK(b.kind != BlockKind::Unknown);
				if (b.kind == BlockKind::Table)
				{
					++tables;
					CHECK(!b.rows.empty());
				}
				if (b.kind == BlockKind::Code)
				{
					++code;
					CHECK(!b.text.empty());
				}
			}
		}
	}
	CHECK(sections >= 60);
	// The reference pages are mostly tables and listings; if the converter ever
	// flattens them to paragraphs these two counts are what says so.
	CHECK(tables >= 20);
	CHECK(code >= 5);
	INFO("pages=" << lib.pages().size() << " sections=" << sections
	              << " blocks=" << blocks << " tables=" << tables);
}

TEST_CASE("docs bundle: every internal link points at something that exists")
{
	Library lib = loadShipped();
	REQUIRE(lib.loaded());

	// Cross references between docs pages are rewritten as topic refs; a broken
	// one is a dead end in the reader, where — unlike a browser — there is no
	// address bar to recover from it.
	int checked = 0;
	auto checkRuns = [&](const std::vector<Run>& runs) {
		for (const Run& r : runs)
		{
			if (r.style != Style::Link || r.href.empty()) continue;
			if (r.href.rfind("http", 0) == 0 || r.href.rfind("mailto:", 0) == 0) continue;
			if (r.href[0] == '#') continue;   // same-page anchor
			int page = -1, section = -1;
			CHECK_MESSAGE(lib.resolve(r.href, page, section), "dangling docs link: ", r.href);
			++checked;
		}
	};

	// Blocks nest one level (callouts hold paragraphs), so this walks rather
	// than iterating — a link inside a callout is still a link.
	auto walk = [&](auto&& self, const Block& b) -> void {
		checkRuns(b.runs);
		for (const Cell& c : b.items) checkRuns(c);
		for (const Cell& c : b.head)  checkRuns(c);
		for (const Cells& row : b.rows)
			for (const Cell& c : row) checkRuns(c);
		for (const Block& inner : b.blocks) self(self, inner);
	};
	for (const Page& p : lib.pages())
		for (const Section& s : p.sections)
			for (const Block& b : s.blocks) walk(walk, b);

	INFO("internal links checked: " << checked);
	CHECK(checked > 0);
}

TEST_CASE("docs bundle: figures name a file that was actually copied")
{
	Library lib = loadShipped();
	REQUIRE(lib.loaded());
	for (const Page& p : lib.pages())
		for (const Section& s : p.sections)
			for (const Block& b : s.blocks)
				if (b.kind == BlockKind::Figure)
				{
					CHECK(!b.src.empty());
					// No directory parts: the reader joins this onto Docs/img/, and a
					// "../" in a data file must never escape that.
					CHECK(b.src.find('/') == std::string::npos);
					CHECK(b.src.find('\\') == std::string::npos);
					CHECK(b.src.find("..") == std::string::npos);
				}
}

TEST_CASE("docs library: blocks survive the round trip")
{
	Library lib;
	REQUIRE(lib.loadFromJson(kMiniBundle));
	REQUIRE(lib.pages().size() == 2);

	const Section& shadows = lib.pages()[0].sections[0];
	REQUIRE(shadows.blocks.size() == 3);

	CHECK(shadows.blocks[0].kind == BlockKind::Lead);
	REQUIRE(shadows.blocks[0].runs.size() == 3);
	CHECK(shadows.blocks[0].runs[1].text == "shadow maps");
	CHECK(shadows.blocks[0].runs[1].style == Style::Bold);

	CHECK(shadows.blocks[1].kind == BlockKind::Table);
	REQUIRE(shadows.blocks[1].head.size() == 1);
	REQUIRE(shadows.blocks[1].rows.size() == 1);
	CHECK(shadows.blocks[1].rows[0][0][0].style == Style::Code);

	CHECK(shadows.blocks[2].kind == BlockKind::Callout);
	CHECK(shadows.blocks[2].tone == Tone::Warning);
	REQUIRE(shadows.blocks[2].blocks.size() == 1);
	CHECK(shadows.blocks[2].blocks[0].runs[0].text == "Metal only.");

	const Section& listings = lib.pages()[1].sections[0];
	REQUIRE(listings.blocks.size() == 4);
	CHECK(listings.blocks[0].kind == BlockKind::Code);
	CHECK(listings.blocks[0].title == "spin.lua");
	CHECK(listings.blocks[0].text.find('\n') != std::string::npos);
	CHECK(listings.blocks[1].items.size() == 2);
	CHECK(listings.blocks[2].src == "shot.jpg");
	REQUIRE(listings.blocks[3].steps.size() == 1);
	CHECK(listings.blocks[3].steps[0].label == "Extract");
}

TEST_CASE("docs library: topics resolve, and a stale anchor still lands on its page")
{
	Library lib;
	REQUIRE(lib.loadFromJson(kMiniBundle));

	int page = -1, section = -1;
	CHECK(lib.resolve("alpha#shadows", page, section));
	CHECK(page == 0);
	CHECK(section == 0);

	CHECK(lib.resolve("alpha", page, section));
	CHECK(page == 0);
	CHECK(section == -1);

	// The website spelling of the same topic.
	CHECK(lib.resolve("alpha.html#misc", page, section));
	CHECK(page == 0);
	CHECK(section == 1);

	// A section that was renamed: the page is still the right answer.
	CHECK(lib.resolve("alpha#gone", page, section));
	CHECK(page == 0);
	CHECK(section == -1);

	// A page that does not exist is a miss, not a silent first page.
	CHECK_FALSE(lib.resolve("nope#shadows", page, section));
	CHECK(page == -1);
	CHECK_FALSE(lib.resolve("", page, section));

	CHECK(lib.topicOf(0, 0) == "alpha#shadows");
	CHECK(lib.topicOf(0, -1) == "alpha");
	CHECK(lib.url(0, 0) == "https://example.invalid/docs/alpha.html#shadows");
	CHECK(lib.url(1, -1) == "https://example.invalid/docs/beta.html");
}

TEST_CASE("docs search: the heading beats the passing mention")
{
	Library lib;
	REQUIRE(lib.loadFromJson(kMiniBundle));

	const std::vector<Hit> hits = lib.search("shadow");
	REQUIRE(hits.size() >= 2);
	CHECK(firstTitle(lib, hits) == "Shadows");
	CHECK(hits[0].score > hits[1].score);
	CHECK(!hits[0].snippet.empty());

	// Every word has to appear somewhere, or a two-word query would return the
	// whole manual sorted by coincidence.
	CHECK(lib.search("shadow maps").size() == 1);
	CHECK(lib.search("shadow unicorn").empty());
	CHECK(lib.search("").empty());
	CHECK(lib.search("   ").empty());

	// Punctuation is a separator, not a character to match: people paste
	// "M.onUpdate(self, dt)" out of a listing.
	CHECK(lib.search("onUpdate()").size() == 1);
	CHECK(lib.search("ONUPDATE").size() == 1);

	// maxHits is a cap, not a suggestion.
	CHECK(lib.search("shadow", 1).size() == 1);
}

TEST_CASE("docs search: a word is not matched inside another word")
{
	Library lib;
	REQUIRE(lib.loadFromJson(kMiniBundle));

	// "Miscellany" is the only section mentioning "highlight", and nothing in the
	// bundle contains the word "light" on its own — except the eyebrow
	// "Lighting", which legitimately starts with it. So a search for "light"
	// finds "Shadows" through its eyebrow and must NOT find "Miscellany", where
	// the letters only occur inside another word.
	const std::vector<Hit> hits = lib.search("light");
	REQUIRE(!hits.empty());
	for (const Hit& h : hits)
		CHECK(lib.pages()[h.page].sections[h.section].title != "Miscellany");
	CHECK(firstTitle(lib, hits) == "Shadows");

	// The word itself still matches, prefix and all.
	CHECK(firstTitle(lib, lib.search("highlight")) == "Miscellany");

	// Plural and singular find each other, because people type the form they
	// think in, not the form the heading uses.
	CHECK(firstTitle(lib, lib.search("shadows")) == "Shadows");
	CHECK(firstTitle(lib, lib.search("listing")) == "Listings");
}

TEST_CASE("docs search: the shipped manual answers the questions it exists for")
{
	Library lib = loadShipped();
	REQUIRE(lib.loaded());

	// Not "these exact sections rank first" — the docs get reworded. What is
	// asserted is that a plain question about a thing the editor HAS comes back
	// with something, on the page it belongs to. A rewrite that empties one of
	// these is a docs bug worth a red test.
	struct Q { const char* query; const char* expectPage; };
	const Q queries[] = {
		{ "play mode",        "editor" },
		{ "content browser",  "editor" },
		{ "shortcuts",        "editor" },
		{ "material graph",   "materials" },
		{ "particle",         nullptr },
		{ "navmesh",          nullptr },
		{ "export",           "export" },
		{ "collaboration",    "collaboration" },
		{ "horizoncode",      nullptr },
		{ "sky",              nullptr },
	};
	for (const Q& q : queries)
	{
		const std::vector<Hit> hits = lib.search(q.query);
		// Comma-chained, not "<<": doctest builds the message with its own
		// operator*, which binds tighter than either + or <<, so an expression
		// built with those falls apart into (builder * first) + rest.
		CHECK_MESSAGE(!hits.empty(), "no docs hit for query: ", q.query);
		if (hits.empty() || !q.expectPage) continue;
		bool onExpected = false;
		for (int i = 0; i < static_cast<int>(hits.size()) && i < 5; ++i)
			if (lib.pages()[hits[i].page].id == q.expectPage) onExpected = true;
		CHECK_MESSAGE(onExpected, "query '", q.query, "' has no top-5 hit on page '",
		              q.expectPage, "' (best: ", firstTitle(lib, hits), ")");
	}
}

TEST_CASE("docs library: a broken bundle fails loudly and leaves nothing behind")
{
	Library lib;
	REQUIRE(lib.loadFromJson(kMiniBundle));
	REQUIRE(lib.loaded());

	// Each of these must clear the previously loaded content rather than leave a
	// half-parsed mixture of the two.
	CHECK_FALSE(lib.loadFromJson("{ not json"));
	CHECK_FALSE(lib.loaded());
	CHECK(!lib.error().empty());
	CHECK(lib.search("shadow").empty());

	CHECK_FALSE(lib.loadFromJson(R"({"version":1,"pages":[]})"));
	CHECK_FALSE(lib.loaded());

	// A bundle from a newer generator is refused: an unknown block kind would
	// vanish from the page, and a reader cannot tell a missing paragraph from a
	// paragraph that was never written.
	CHECK_FALSE(lib.loadFromJson(R"({"version":99,"pages":[{"id":"a","sections":[]}]})"));
	CHECK(lib.error().find("newer") != std::string::npos);

	CHECK_FALSE(lib.load("/nonexistent/he-docs.json"));
	CHECK(lib.error().find("could not open") != std::string::npos);
}

TEST_CASE("docs library: bundle paths follow the deploy layout")
{
	// EditorDeps is copied wholesale next to the executable, so the manual sits
	// beside Fonts/ and Images/ — the same base path SDL reports.
	CHECK(bundlePath("/opt/HorizonEditor/") == "/opt/HorizonEditor/Docs/he-docs.json");
	CHECK(imageDir("/opt/HorizonEditor/") == "/opt/HorizonEditor/Docs/img/");
	CHECK(bundlePath("") == "Docs/he-docs.json");
}
