// ═══ The shipped engine materials (EditorDeps/EngineContent/Materials) ═══════
// Generated by mat_gen and COMMITTED, so nothing rebuilds them on the way to
// this test — which is exactly why it needs one. Every project sees these in
// its Content Browser and material picker, and an export packs them with the
// shader BAKED into the file (HpakWriter copies customShaderFragGlsl verbatim),
// not the one the editor regenerates at load. So both are checked: what the
// editor makes of the file, and what the file itself would ship.
//
// Water (docs/water-shader-plan.md, Thema 152).

#include "doctest.h"

#include <ContentManager/Assets.h>
#include <ContentManager/ContentManager.h>
#include <ContentManager/DefaultAssets.h>
#include <ContentManager/HAsset.h>
#include <MaterialGraph/MaterialGraph.h>

#include <chrono>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <set>
#include <string>
#include <vector>

#if defined(HE_TESTS_HAVE_SHADERC)
#include <material/MaterialShaderLibrary.h>
#if defined(_WIN32)
#ifndef NOMINMAX
#define NOMINMAX
#endif
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#include <d3dcompiler.h>
#include <wrl/client.h>
#endif
#endif

#ifdef HE_EDITOR_DEPS_DIR
namespace
{
namespace fs = std::filesystem;
using HE::MatParamKind;

const fs::path& engineRoot()
{
	static const fs::path p = fs::path(HE_EDITOR_DEPS_DIR) / "EngineContent";
	return p;
}
constexpr const char* kWaterPath = "Engine/Materials/Water.hasset";

// A throwaway project (and, where a test saves, a throwaway COPY of the engine
// root): a save must never be able to reach EditorDeps, whatever
// HE_ENGINE_CONTENT_EDITABLE says on the machine running the suite.
struct Scratch
{
	fs::path path;
	explicit Scratch(const char* tag)
	{
		path = fs::temp_directory_path() /
		       (std::string("he_engine_mat_") + tag + "_" +
		        std::to_string(std::chrono::steady_clock::now().time_since_epoch().count()));
		std::error_code ec;
		fs::remove_all(path, ec);
		fs::create_directories(path / "Content");
	}
	~Scratch() { std::error_code ec; fs::remove_all(path, ec); }
	std::string content() const { return (path / "Content").string(); }
};

// What the water promises: every knob, its widget kind and its authored default.
// The defaults are duplicated from mat_gen on purpose — retuning the water is a
// change this list has to be shown.
struct Knob { const char* name; MatParamKind kind; float v[4]; };
const Knob kWaterKnobs[] = {
	{ "ShallowColor", MatParamKind::Color, { 0.10f, 0.42f, 0.45f, 0.0f } },
	{ "DeepColor",    MatParamKind::Color, { 0.01f, 0.07f, 0.12f, 0.0f } },
	{ "Turbidity",    MatParamKind::Vec2,  { 0.35f, 3.0f, 0.0f, 0.0f } },
	{ "WaveA",        MatParamKind::Vec4,  { 30.0f, 1.2f, 8.0f, 0.25f } },
	{ "WaveB",        MatParamKind::Vec4,  { 310.0f, 0.8f, 3.5f, 0.18f } },
	{ "WaveC",        MatParamKind::Vec4,  { 100.0f, 0.5f, 1.2f, 0.12f } },
	{ "FresnelPower", MatParamKind::Float, { 5.0f, 0.0f, 0.0f, 0.0f } },
	{ "Reflection",   MatParamKind::Float, { 0.8f, 0.0f, 0.0f, 0.0f } },
	{ "Roughness",    MatParamKind::Float, { 0.06f, 0.0f, 0.0f, 0.0f } },
	{ "Specular",     MatParamKind::Float, { 0.3f, 0.0f, 0.0f, 0.0f } },
	{ "Opacity",      MatParamKind::Float, { 0.55f, 0.0f, 0.0f, 0.0f } },
	{ "Refraction",   MatParamKind::Float, { 0.3f, 0.0f, 0.0f, 0.0f } },
	{ "FoamColor",    MatParamKind::Color, { 0.92f, 0.95f, 0.97f, 0.0f } },
	{ "Foam",         MatParamKind::Vec4,  { 0.18f, 0.8f, 1.5f, 0.3f } },
	{ "Caustics",     MatParamKind::Vec4,  { 0.35f, 2.5f, 0.25f, 25.0f } },
};
constexpr int kWaterKnobCount = static_cast<int>(sizeof(kWaterKnobs) / sizeof(kWaterKnobs[0]));

int slotOf(const MaterialAsset& m, const char* name)
{
	for (size_t i = 0; i < m.graphParamNames.size(); ++i)
		if (m.graphParamNames[i] == name) return static_cast<int>(i);
	return -1;
}

std::string readFile(const fs::path& p)
{
	std::ifstream f(p, std::ios::binary);
	return std::string(std::istreambuf_iterator<char>(f), std::istreambuf_iterator<char>());
}

// The fragment and the parameter names exactly as they sit in the FILE — the
// MTRL field walk HpakWriter does, because loadAsset regenerates and would hide
// a stale bake.
struct Baked { std::string frag; std::vector<std::string> paramNames; bool ok = false; };
Baked readBaked(const fs::path& file)
{
	Baked b;
	HAsset::Reader r;
	if (!r.open(file.string())) return b;
	const auto* c = r.findChunk(HAsset::CHUNK_MTRL);
	if (!c) return b;
	size_t o = 0;
	std::string str; std::vector<std::string> vs; float f = 0; uint32_t n = 0;
	if (!HAsset::Reader::readString(c->data, o, str)) return b;          // shaderPath
	if (!HAsset::Reader::readVec(c->data, o, vs)) return b;              // texturePaths
	for (int i = 0; i < 6; ++i)
		if (!HAsset::Reader::readPOD(c->data, o, f)) return b;           // PBR scalars
	if (!HAsset::Reader::readString(c->data, o, b.frag)) return b;       // customShaderFragGlsl
	if (!HAsset::Reader::readString(c->data, o, str)) return b;          // nodeGraphJson
	if (!HAsset::Reader::readPOD(c->data, o, n)) return b;               // shaderParamData
	for (uint32_t i = 0; i < n; ++i)
		if (!HAsset::Reader::readPOD(c->data, o, f)) return b;
	if (!HAsset::Reader::readVec(c->data, o, vs)) return b;              // graphTexturePaths
	if (!HAsset::Reader::readVec(c->data, o, b.paramNames)) return b;    // graphParamNames
	b.ok = true;
	return b;
}
} // namespace

TEST_CASE("Engine water material: loads as a lit Translucent graph with all fifteen knobs")
{
	REQUIRE(fs::exists(engineRoot() / "Materials" / "Water.hasset"));
	Scratch s("load");
	ContentManager cm(s.content());
	cm.setEngineContentRoot(engineRoot().string());

	const HE::UUID id = cm.loadAsset(kWaterPath);
	// The UUID code finds it by — DefaultAssets.h and mat_gen's block agree.
	CHECK(id == HE::kEngineWaterMaterialId);
	const MaterialAsset* m = cm.getMaterial(id);
	REQUIRE(m);

	CHECK(m->blendMode == static_cast<uint8_t>(HE::MatBlendMode::Translucent));
	CHECK(m->domain == static_cast<uint8_t>(HE::MatDomain::Surface));
	HE::MaterialGraph g;
	REQUIRE(HE::materialGraphFromJson(m->nodeGraphJson, g));
	bool lit = false;
	for (const HE::MatGraphNode& n : g.nodes)
		if (n.type == HE::MatNodeType::Output) lit = n.p[0] > 0.5f;
	CHECK(lit);   // the sky reflection and the sun glint come from heLitP

	// Nothing a project might not have: no texture, no mem:// default (an export
	// cannot resolve one), and no WPO — the engine plane is a single quad.
	CHECK(m->graphTexturePaths.empty());
	CHECK(m->nodeGraphJson.find("mem://") == std::string::npos);
	CHECK(m->customShaderVertGlsl.empty());

	// Every knob is exposed — an unwired or over-budget Param node would be
	// missing here, not erroring anywhere — with its kind, default and the
	// metadata the parameter panels show.
	REQUIRE(static_cast<int>(m->graphParamNames.size()) == kWaterKnobCount);
	REQUIRE(m->graphParamTypes.size() == m->graphParamNames.size());
	REQUIRE(m->shaderParamData.size() == m->graphParamNames.size() * 4);
	REQUIRE(m->graphParamMinMax.size() == m->graphParamNames.size() * 2);
	REQUIRE(m->graphParamGroups.size() == m->graphParamNames.size());
	REQUIRE(m->graphParamTooltips.size() == m->graphParamNames.size());
	for (const Knob& k : kWaterKnobs)
	{
		CAPTURE(std::string(k.name));
		const int i = slotOf(*m, k.name);
		REQUIRE(i >= 0);
		CHECK(m->graphParamTypes[i] == static_cast<uint8_t>(k.kind));
		for (int c = 0; c < HE::matParamKindComponents(k.kind); ++c)
			CHECK(m->shaderParamData[i * 4 + c] == doctest::Approx(k.v[c]));
		CHECK_FALSE(m->graphParamGroups[i].empty());
		CHECK_FALSE(m->graphParamTooltips[i].empty());
		if (k.kind == MatParamKind::Float)
			CHECK(m->graphParamMinMax[i * 2] < m->graphParamMinMax[i * 2 + 1]);   // a slider
	}

	// The shader reads every slot and the clock (the waves move).
	for (int i = 0; i < kWaterKnobCount; ++i)
		CHECK_MESSAGE(m->customShaderFragGlsl.find("heParams.v[" + std::to_string(i) + "]") != std::string::npos,
		              "slot ", i, " is never read");
	CHECK(m->customShaderFragGlsl.find("heLight.sunDir.w") != std::string::npos);
}

TEST_CASE("Engine water material: an edited value survives save and reload, the default does not move")
{
	Scratch s("save");
	// A COPY of the engine root, so even a dev-mode save (which writes the
	// default in place) lands in the scratch tree.
	const fs::path engineCopy = s.path / "Engine";
	fs::create_directories(engineCopy / "Materials");
	const fs::path shipped = engineRoot() / "Materials" / "Water.hasset";
	REQUIRE(fs::copy_file(shipped, engineCopy / "Materials" / "Water.hasset"));
	const std::string shippedBytes = readFile(shipped);

	{
		ContentManager cm(s.content());
		cm.setEngineContentRoot(engineCopy.string());
		const HE::UUID id = cm.loadAsset(kWaterPath);
		REQUIRE(id == HE::kEngineWaterMaterialId);
		MaterialAsset* m = cm.getMaterialMutable(id);
		REQUIRE(m);
		const int wave = slotOf(*m, "WaveA");
		const int col  = slotOf(*m, "ShallowColor");
		const int opa  = slotOf(*m, "Opacity");
		REQUIRE(wave >= 0); REQUIRE(col >= 0); REQUIRE(opa >= 0);
		const float waveV[4] = { 45.0f, 2.0f, 10.0f, 0.3f };
		for (int c = 0; c < 4; ++c) m->shaderParamData[wave * 4 + c] = waveV[c];
		m->shaderParamData[col * 4 + 0] = 0.2f;
		m->shaderParamData[col * 4 + 1] = 0.5f;
		m->shaderParamData[col * 4 + 2] = 0.3f;
		m->shaderParamData[opa * 4 + 0] = 0.75f;
		REQUIRE(cm.saveAsset(*m));
	}

	// Normal mode: the save is a project OVERRIDE under Content/Engine/…, and
	// the shared default stays byte for byte what was shipped.
	if (!ContentManager::isEngineContentDevMode())
	{
		CHECK(fs::exists(s.path / "Content" / "Engine" / "Materials" / "Water.hasset"));
		CHECK(readFile(engineCopy / "Materials" / "Water.hasset") == shippedBytes);
	}

	ContentManager cm(s.content());
	cm.setEngineContentRoot(engineCopy.string());
	const HE::UUID id = cm.loadAsset(kWaterPath);
	CHECK(id == HE::kEngineWaterMaterialId);
	const MaterialAsset* m = cm.getMaterial(id);
	REQUIRE(m);
	// The reload regenerates the shader from the graph and keeps values BY NAME.
	REQUIRE(static_cast<int>(m->graphParamNames.size()) == kWaterKnobCount);
	const int wave = slotOf(*m, "WaveA");
	const int col  = slotOf(*m, "ShallowColor");
	const int opa  = slotOf(*m, "Opacity");
	const int deep = slotOf(*m, "DeepColor");
	REQUIRE(wave >= 0); REQUIRE(col >= 0); REQUIRE(opa >= 0); REQUIRE(deep >= 0);
	CHECK(m->shaderParamData[wave * 4 + 0] == doctest::Approx(45.0f));
	CHECK(m->shaderParamData[wave * 4 + 1] == doctest::Approx(2.0f));
	CHECK(m->shaderParamData[wave * 4 + 2] == doctest::Approx(10.0f));
	CHECK(m->shaderParamData[wave * 4 + 3] == doctest::Approx(0.3f));
	CHECK(m->shaderParamData[col * 4 + 0] == doctest::Approx(0.2f));
	CHECK(m->shaderParamData[col * 4 + 1] == doctest::Approx(0.5f));
	CHECK(m->shaderParamData[col * 4 + 2] == doctest::Approx(0.3f));
	CHECK(m->shaderParamData[opa * 4 + 0] == doctest::Approx(0.75f));
	// …and an untouched knob keeps its default.
	CHECK(m->shaderParamData[deep * 4 + 0] == doctest::Approx(0.01f));
	CHECK(m->shaderParamData[deep * 4 + 2] == doctest::Approx(0.12f));
}

TEST_CASE("Engine water material: the committed file carries a shader, not just the graph")
{
	// What an export ships. A file holding only the graph would pack as the
	// built-in PBR shader; mat_gen bakes on purpose (its header says why).
	const Baked b = readBaked(engineRoot() / "Materials" / "Water.hasset");
	REQUIRE(b.ok);
	REQUIRE_FALSE(b.frag.empty());
	const std::set<std::string> baked(b.paramNames.begin(), b.paramNames.end());
	std::set<std::string> want;
	for (const Knob& k : kWaterKnobs) want.insert(k.name);
	CHECK(baked == want);
	for (int i = 0; i < kWaterKnobCount; ++i)
		CHECK(b.frag.find("heParams.v[" + std::to_string(i) + "]") != std::string::npos);
	CHECK(b.frag.find("heLight.sunDir.w") != std::string::npos);
}

#if defined(HE_TESTS_HAVE_SHADERC)
TEST_CASE("Engine water material: the editor's shader and the shipped one cross-compile for every backend")
{
	Scratch s("compile");
	ContentManager cm(s.content());
	cm.setEngineContentRoot(engineRoot().string());
	const HE::UUID id = cm.loadAsset(kWaterPath);
	const MaterialAsset* m = cm.getMaterial(id);
	REQUIRE(m);
	const Baked b = readBaked(engineRoot() / "Materials" / "Water.hasset");
	REQUIRE(b.ok);

	struct Src { const char* what; std::string glsl; };
	const Src sources[] = {
		{ "regenerated forward fragment", m->customShaderFragGlsl },
		{ "regenerated G-buffer fragment", m->customShaderGBufGlsl },
		{ "baked forward fragment (what an export ships)", b.frag },
	};

	using B = HE::MaterialShaderLibrary::Backend;
	HE::MaterialShaderLibrary lib;
	for (const Src& src : sources)
	{
		CAPTURE(std::string(src.what));
		REQUIRE_FALSE(src.glsl.empty());
		const uint64_t h = std::hash<std::string>{}(src.glsl);
		for (B be : { B::Metal, B::GLSL410, B::GLSLES300, B::HLSL, B::SpirV })
		{
			const auto& c = lib.fragment(h, src.glsl, be);
			CHECK_MESSAGE(c.ok, std::string(src.what), " failed for backend ", static_cast<int>(be), ": ", c.log);
		}
	}

#if defined(_WIN32)
	// D3D11/D3D12 hand the HLSL to FXC (ps_5_0, entry "main") — SPIRV-Cross's
	// "ok" says nothing about register limits or intrinsic spelling.
	for (const Src& src : sources)
	{
		CAPTURE(std::string(src.what));
		const std::string& hlsl = lib.fragment(std::hash<std::string>{}(src.glsl), src.glsl, B::HLSL).source;
		REQUIRE_FALSE(hlsl.empty());
		Microsoft::WRL::ComPtr<ID3DBlob> blob, err;
		const HRESULT hr = D3DCompile(hlsl.c_str(), hlsl.size(), "water", nullptr, nullptr,
		                              "main", "ps_5_0", 0, 0, &blob, &err);
		std::string log;
		if (err) log.assign(static_cast<const char*>(err->GetBufferPointer()), err->GetBufferSize());
		CHECK_MESSAGE(SUCCEEDED(hr), std::string(src.what), ": ", log);
	}
#endif
}
#endif // HE_TESTS_HAVE_SHADERC
#endif // HE_EDITOR_DEPS_DIR
