#pragma once
#include "../HE_RENDERING_API.h"
#include <cstdint>
#include <vector>

// ─── Procedural 3D sky/cloud noise volume (shared by every backend) ───────────
// Was duplicated verbatim in all five backends. The generated BYTES are a
// cross-backend contract: the "pixelige Wolken" fix replaced the old 2D FBM with
// this 3D volume and the result was verified byte-identical across backends, so
// any change here changes the look of the sky on every platform at once. There is
// a hash pin in tests/test_culling.cpp guarding exactly that — if you change the
// generator you must consciously re-pin it.
namespace HE
{

// Builds a tiling NxNxN two-channel noise volume (interleaved RG16):
//   R = value noise whose lattice values are exactly the sky shader's
//       starHash(i,j,k). With the shader pre-smoothstepping the fractional sample
//       coordinate, the GPU's trilinear filter reproduces the old smoothstep value
//       noise exactly (within one tile) — so starFbm3 stays a texture fetch with no
//       visible change (nebula/stars unaffected, byte-for-byte).
//   G = tiling inverted-Worley (cellular) field, bright at the cell feature points.
//       fBm of this is the billowy "cauliflower" shape that turns the clouds from
//       wispy value-noise blobs into rounded cumuli. Worley is C0-smooth so plain
//       trilinear sampling of the bake is fine (no pre-smoothstep trick needed).
// R16-per-channel keeps the threshold ramps band-free.
//
// Serial nested loops (one-time init): each voxel is fully independent, but the
// parallel STL is unusable here — <execution> is unimplemented in libc++/Apple
// Clang, and a parallel bake must not be allowed to reorder into different bytes.
HE_RENDERING_API std::vector<uint16_t> BuildSkyNoise3D(int n);

} // namespace HE
