#pragma once
#include <Types/UUID.h>
#include <Math/Math.h>
#include <vector>

// Scatters foliage mesh instances across the terrain of the same entity.
// FoliageSystem::update() computes cachedInstances when dirty is true.
// RenderExtractor reads cachedInstances and pushes them as RenderObjects
// (existing same-mesh batching handles the GPU instancing automatically).
struct FoliageComponent {
    bool     visible = true;    // extractor skips invisible (zone hiding)
    HE::UUID meshAssetId;
    HE::UUID materialAssetId;
    float    density      = 0.1f;    // instances per unit area
    int      seed         = 42;
    float    minScale     = 0.8f;
    float    maxScale     = 1.2f;
    float    drawDistance = 80.f;    // instances beyond this distance are not submitted
    bool     dirty        = true;    // set true to regenerate cachedInstances

    // ── Painted density mask ────────────────────────────────────────────────
    // One byte per texel, row-major over the terrain's 0..1 UV range like the
    // terrain's layerWeights: 255 = the full `density`, 0 = nothing grows here
    // (an exclusion area — a road, a yard, a lake), anything between thins the
    // scatter proportionally. EMPTY = unpainted, the layer stays uniform over
    // the whole landscape exactly as before the mask existed, so old scenes
    // and layers nobody painted look the same. FoliagePaint edits it, the
    // Landscape panel's Foliage brush drives that, and FoliageSystem samples it
    // when it scatters. Serialised inline (base64) with the component.
    uint32_t             maskRes = 128;   // mask side length in texels
    std::vector<uint8_t> densityMask;     // maskRes² bytes, or empty

    // Pre-computed per-instance model matrices (world space).
    // Generated by FoliageSystem, consumed by RenderExtractor.
    std::vector<glm::mat4> cachedInstances;
};
