#pragma once
#include <Types/UUID.h>
#include <Math/Math.h>
#include <vector>

// Scatters foliage mesh instances across the terrain of the same entity.
// FoliageSystem::update() computes cachedInstances when dirty is true.
// RenderExtractor reads cachedInstances and pushes them as RenderObjects
// (existing same-mesh batching handles the GPU instancing automatically).
struct FoliageComponent {
    HE::UUID meshAssetId;
    HE::UUID materialAssetId;
    float    density      = 0.1f;    // instances per unit area
    int      seed         = 42;
    float    minScale     = 0.8f;
    float    maxScale     = 1.2f;
    float    drawDistance = 80.f;    // instances beyond this distance are not submitted
    bool     dirty        = true;    // set true to regenerate cachedInstances

    // Pre-computed per-instance model matrices (world space).
    // Generated by FoliageSystem, consumed by RenderExtractor.
    std::vector<glm::mat4> cachedInstances;
};
