#pragma once

#include "HorizonWorld.h"
#include "SceneGraph.h"
#include "SceneSerializer.h"

#include "Components/NameComponent.h"
#include "Components/TransformComponent.h"
#include "Components/Transform2DComponent.h"
#include "Components/HierarchyComponent.h"
#include "Components/MeshComponent.h"
#include "Components/SkeletalMeshComponent.h"
#include "Components/AnimatorComponent.h"
#include "Components/AnimatorBlendComponent.h"
#include "Components/AnimatorStateMachineComponent.h"
#include "Components/PropertyAnimatorComponent.h"
#include "Components/NavMeshComponent.h"
#include "Components/NavAgentComponent.h"
#include "Components/MaterialComponent.h"
#include "Components/CameraComponent.h"
#include "Components/LightComponent.h"
#include "Components/RigidBodyComponent.h"
#include "Components/ColliderComponent.h"
#include "Components/CharacterControllerComponent.h"
#include "Components/ScriptComponent.h"
#include "Components/EnvironmentComponent.h"
#include "Components/EnvironmentLightComponent.h"
#include "Components/WeatherComponent.h"
#include "Components/TerrainComponent.h"
#include "Components/TerrainChunkComponent.h"
#include "Components/AudioSourceComponent.h"
#include "Components/AudioListenerComponent.h"
#include "Components/ParticleSystemComponent.h"
#include "Components/LODComponent.h"
#include "Components/FoliageComponent.h"
#include "LODSystem.h"
#include "FoliageSystem.h"
#include "Components/UICanvasComponent.h"
#include "Components/UIElementComponent.h"
#include "Components/UITextComponent.h"
#include "Components/UIImageComponent.h"
#include "Components/UIButtonComponent.h"
#include "Components/UIWidgetComponent.h"
#include "UISystem.h"
#include "UIWidgetInstantiator.h"
#include "TerrainMeshGenerator.h"
#include "TerrainSystem.h"

// Re-export EnTT entity type
#include <entt/entt.hpp>
using Entity = entt::entity;
