#pragma once
#include <glm/glm.hpp>
#include <memory>
#include <cstdint>
#include <vector>

class HorizonWorld;

// PIMPL wrapper around Jolt PhysicsSystem.
// Keeps all Jolt headers out of the public API.
class PhysicsWorld
{
public:
    // A single contact event between two entities (identified by raw entity handle).
    struct CollisionEvent
    {
        uint32_t entityA = 0;
        uint32_t entityB = 0;
    };

    // Result of a single raycast. `hit` is false when no body was intersected.
    struct RaycastHit
    {
        bool      hit      = false;
        uint32_t  entityId = 0;      // raw entt::entity; cast to Entity for ECS use
        glm::vec3 point    = {};
        glm::vec3 normal   = {};
        float     distance = 0.0f;
    };

    PhysicsWorld();
    ~PhysicsWorld();

    // Build one body per entity that has RigidBodyComponent + TransformComponent.
    // Uses ColliderComponent shape when present; falls back to a box from scale.
    void initialize(HorizonWorld& world);

    // Advance the simulation by dt seconds, then write dynamic/kinematic body
    // positions and orientations back to TransformComponent.
    void step(HorizonWorld& world, float dt);

    // Cast a ray from `origin` along `direction` (need not be normalised) up to
    // `maxDistance` metres. Returns the closest hit or RaycastHit{hit=false}.
    RaycastHit raycast(const glm::vec3& origin,
                       const glm::vec3& direction,
                       float            maxDistance = 1000.0f) const;

    // Set the movement velocity for a CharacterController entity (m/s).
    // Has no effect if the entity has no active character controller.
    void setCharacterVelocity(uint32_t entityId, const glm::vec3& velocity);

    // Returns true if the character's feet are on solid ground.
    bool isCharacterGrounded(uint32_t entityId) const;

    // Drain and return all collision-enter events recorded since the last call.
    // Events are generated by the Jolt contact listener during step(); safe to call
    // every frame whether or not physics was stepped. Reported once per body pair,
    // not once per touching sub shape.
    std::vector<CollisionEvent> pollCollisionEnter();

    // Drain and return all collision-exit events recorded since the last call.
    // Mirrors pollCollisionEnter(): exactly one event per body pair, emitted when
    // the last contact between the two bodies goes away. Pairs whose bodies were
    // destroyed via clear() do not produce an exit event.
    std::vector<CollisionEvent> pollCollisionExit();

    // The same two, for contacts where at least one side is a TRIGGER
    // (ColliderComponent::isTrigger — the body is created as a Jolt sensor, so
    // it passes bodies through and only reports). A contact lands in exactly one
    // of the two pairs, decided when it begins, so a trigger never also shows up
    // as a blocking hit.
    std::vector<CollisionEvent> pollOverlapEnter();
    std::vector<CollisionEvent> pollOverlapExit();

    // Remove and destroy all physics bodies without touching the ECS.
    void clear();

private:
    struct Impl;
    std::unique_ptr<Impl> m_impl;
};
