#include "SourceControl/RepoConfig.h"

#include "ScLog.h"

#include <fstream>

namespace HE::Sc {

std::string RepoConfig::gitignoreText()
{
	// Everything here is REGENERATED by the engine or the toolchain. If a line
	// ever feels wrong, the test is: "would deleting this lose authored work?"
	return
		"# ── Generated by HorizonEngine (git init) ─────────────────────────────\n"
		"# Engine output — regenerated on demand, never authored.\n"
		"Saved/\n"
		"Export/\n"
		"dumps/\n"
		"*.log\n"
		"\n"
		"# Native game-logic build output. GameLogic.hot-* are the hot-reload\n"
		"# copies the editor makes on every reload; they accumulate silently.\n"
		"Source/build/\n"
		"GameLogic.dll\n"
		"GameLogic.dylib\n"
		"GameLogic.so\n"
		"GameLogic.hot-*.*\n"
		"\n"
		"# Compiled shader artifacts.\n"
		"*.spv\n"
		"\n"
		"# OS noise.\n"
		".DS_Store\n"
		"Thumbs.db\n";
}

std::string RepoConfig::gitattributesText()
{
	// LFS carries exactly what the collaboration session refuses to: the large
	// binaries. Authored formats (scenes, graphs, materials …) stay out so they
	// remain diffable — after CP-A their entity ids are stable, so ordinary
	// line merges are safe for scenes; the graph formats keep merge=binary
	// until their node ids grow the same property.
	return
		"# ── Generated by HorizonEngine (git init) ─────────────────────────────\n"
		"* text=auto eol=lf\n"
		"\n"
		"# Large binaries → Git LFS (meshes, textures, audio, video, paks, raw\n"
		"# source art). These are the files that blow past provider limits when\n"
		"# committed directly.\n"
		"*.fbx  filter=lfs diff=lfs merge=lfs -text\n"
		"*.obj  filter=lfs diff=lfs merge=lfs -text\n"
		"*.gltf filter=lfs diff=lfs merge=lfs -text\n"
		"*.glb  filter=lfs diff=lfs merge=lfs -text\n"
		"*.png  filter=lfs diff=lfs merge=lfs -text\n"
		"*.jpg  filter=lfs diff=lfs merge=lfs -text\n"
		"*.jpeg filter=lfs diff=lfs merge=lfs -text\n"
		"*.tga  filter=lfs diff=lfs merge=lfs -text\n"
		"*.exr  filter=lfs diff=lfs merge=lfs -text\n"
		"*.hdr  filter=lfs diff=lfs merge=lfs -text\n"
		"*.psd  filter=lfs diff=lfs merge=lfs -text\n"
		"*.blend filter=lfs diff=lfs merge=lfs -text\n"
		"*.wav  filter=lfs diff=lfs merge=lfs -text\n"
		"*.mp3  filter=lfs diff=lfs merge=lfs -text\n"
		"*.ogg  filter=lfs diff=lfs merge=lfs -text\n"
		"*.flac filter=lfs diff=lfs merge=lfs -text\n"
		"*.mp4  filter=lfs diff=lfs merge=lfs -text\n"
		"*.mov  filter=lfs diff=lfs merge=lfs -text\n"
		"*.hpak filter=lfs diff=lfs merge=lfs -text\n"
		"\n"
		"# Engine assets are containers — a .hasset may hold a mesh or a texture,\n"
		"# so they travel through LFS as well.\n"
		"*.hasset filter=lfs diff=lfs merge=lfs -text\n"
		"\n"
		"# Authored graph formats: allocator-assigned node ids make a line merge\n"
		"# produce a file that parses and is silently wrong. Binary until their\n"
		"# ids are stable the way scene entity ids now are.\n"
		"*.hmat   merge=binary\n"
		"*.hmatfn merge=binary\n"
		"*.hcode  merge=binary\n"
		"*.hpart  merge=binary\n"
		"*.hasm   merge=binary\n"
		"*.huiw   merge=binary\n";
}

bool RepoConfig::writeInitialFiles(const std::filesystem::path& root, std::string* err)
{
	const auto writeIfAbsent = [&](const char* name, const std::string& text) -> bool {
		const std::filesystem::path p = root / name;
		std::error_code ec;
		if (std::filesystem::exists(p, ec))
		{
			// The user's file. Regenerating over it would silently delete their
			// additions — the one thing this writer must never do.
			HE_SC_INFO("%s already exists — left untouched", name);
			return true;
		}
		std::ofstream out(p, std::ios::binary | std::ios::trunc);
		if (!out)
		{
			if (err) *err = std::string("could not write ") + name;
			return false;
		}
		out.write(text.data(), static_cast<std::streamsize>(text.size()));
		if (!out)
		{
			if (err) *err = std::string("could not write ") + name;
			return false;
		}
		HE_SC_INFO("Wrote %s", name);
		return true;
	};

	return writeIfAbsent(".gitignore", gitignoreText()) &&
	       writeIfAbsent(".gitattributes", gitattributesText());
}

} // namespace HE::Sc
