#include "SourceControl/RepoConfig.h"

#include "ScLog.h"

#include <cctype>
#include <fstream>

namespace HE::Sc {

std::string RepoConfig::gitignoreText()
{
	// Everything here is REGENERATED by the engine or the toolchain. If a line
	// ever feels wrong, the test is: "would deleting this lose authored work?"
	return
		"# ── Generated by HorizonEngine (git init) ─────────────────────────────\n"
		"# Engine output — regenerated on demand, never authored.\n"
		"Saved/\n"
		"Export/\n"
		"dumps/\n"
		"*.log\n"
		"\n"
		"# Native game-logic build output. GameLogic.hot-* are the hot-reload\n"
		"# copies the editor makes on every reload; they accumulate silently.\n"
		"Source/build/\n"
		"GameLogic.dll\n"
		"GameLogic.dylib\n"
		"GameLogic.so\n"
		"GameLogic.hot-*.*\n"
		"\n"
		"# Compiled shader artifacts.\n"
		"*.spv\n"
		"\n"
		"# OS noise.\n"
		".DS_Store\n"
		"Thumbs.db\n";
}

std::string RepoConfig::gitattributesText()
{
	// Deliberately NO blanket LFS globs. LFS is routed per file, by size, at
	// commit time (see the CommitAll pre-pass): only meshes, textures and audio
	// that are actually near the provider limit get an entry appended here by
	// `git lfs track`. A pattern like `*.png filter=lfs` would drag every icon
	// into LFS — and on GitHub, LFS bandwidth is the resource that runs out.
	//
	// Authored formats stay diffable — after CP-A their entity ids are stable,
	// so ordinary line merges are safe for scenes; the graph formats keep
	// merge=binary until their node ids grow the same property.
	return
		"# ── Generated by HorizonEngine (git init) ─────────────────────────────\n"
		"* text=auto eol=lf\n"
		"\n"
		"# Large media (meshes, textures, audio over the size threshold) is\n"
		"# tracked through Git LFS per file: the editor appends `git lfs track`\n"
		"# entries below at commit time, so small assets stay in plain git.\n"
		"\n"
		"# Authored graph formats: allocator-assigned node ids make a line merge\n"
		"# produce a file that parses and is silently wrong. Binary until their\n"
		"# ids are stable the way scene entity ids now are.\n"
		"*.hmat   merge=binary\n"
		"*.hmatfn merge=binary\n"
		"*.hcode  merge=binary\n"
		"*.hpart  merge=binary\n"
		"*.hasm   merge=binary\n"
		"*.huiw   merge=binary\n";
}

bool RepoConfig::isAutoLfsCandidate(const std::string& repoRelativePath)
{
	const std::size_t dot = repoRelativePath.find_last_of('.');
	if (dot == std::string::npos) return false;
	std::string ext = repoRelativePath.substr(dot);
	for (char& c : ext) c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));

	// Meshes, textures, audio — the categories that legitimately grow past the
	// limit — plus .hasset, the container those imports live in. Everything
	// else oversized is refused at commit with its name, because the push
	// would bounce anyway and by then it is a history-rewrite problem.
	static const char* kMedia[] = {
		// meshes / raw source art
		".fbx", ".obj", ".gltf", ".glb", ".blend",
		// textures
		".png", ".jpg", ".jpeg", ".tga", ".exr", ".hdr", ".psd",
		".tif", ".tiff", ".dds", ".ktx2",
		// audio
		".wav", ".mp3", ".ogg", ".flac", ".aiff",
		// engine containers for exactly these imports
		".hasset",
	};
	for (const char* m : kMedia)
	{
		if (ext == m) return true;
	}
	return false;
}

bool RepoConfig::writeInitialFiles(const std::filesystem::path& root, std::string* err)
{
	const auto writeIfAbsent = [&](const char* name, const std::string& text) -> bool {
		const std::filesystem::path p = root / name;
		std::error_code ec;
		if (std::filesystem::exists(p, ec))
		{
			// The user's file. Regenerating over it would silently delete their
			// additions — the one thing this writer must never do.
			HE_SC_INFO("%s already exists — left untouched", name);
			return true;
		}
		std::ofstream out(p, std::ios::binary | std::ios::trunc);
		if (!out)
		{
			if (err) *err = std::string("could not write ") + name;
			return false;
		}
		out.write(text.data(), static_cast<std::streamsize>(text.size()));
		if (!out)
		{
			if (err) *err = std::string("could not write ") + name;
			return false;
		}
		HE_SC_INFO("Wrote %s", name);
		return true;
	};

	return writeIfAbsent(".gitignore", gitignoreText()) &&
	       writeIfAbsent(".gitattributes", gitattributesText());
}

} // namespace HE::Sc
